name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout kode dari repositori
    - name: Checkout code
      uses: actions/checkout@v2

    # Install OpenJDK 8
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adoptopenjdk'

    # Install Gradle
    - name: Install Gradle
      run: |
        wget https://services.gradle.org/distributions/gradle-6.8-bin.zip
        unzip gradle-6.8-bin.zip
        sudo mv gradle-6.8 /opt/gradle
        sudo ln -s /opt/gradle/bin/gradle /usr/local/bin/gradle

    # Build aplikasi Android menggunakan Gradle
    - name: Build APK
      run: ./gradlew assembleDebug
