name: Android Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout kode dari repositori
    - name: Checkout code
      uses: actions/checkout@v2

    # Install OpenJDK 11 (lebih stabil untuk Gradle terbaru)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'

    # Install SDKMAN! dan Gradle versi terbaru
    - name: Install Gradle via SDKMAN
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "$HOME/.sdkman/bin/sdkman-init.sh"
        sdk install gradle

    # Build aplikasi Android menggunakan Gradle
    - name: Build APK
      run: ./gradlew assembleDebug
